### ISSUE TITLE
Disk Write Speed at ~400MB per minute

### ISSUE THREAD

**Issue by valoricDe** [jardenliu/XPS15-9560-Catalina#107]
Hi the disk speed is very slow. The strange thing is that it boots up fine and normal operation also seems to be fine. But the write speed is really slow. Do you have ideas with which config I could tweak? I have a 512byte sector size disk in case this matters.

**Comment by SilentSliver** [comment]
Which disk do you use? Toshiba XG4?

**Comment by valoricDe** [comment]
PC401 NVMe SK hynix 512GB it is called

**Comment by jardenliu** [comment]
The speed test was performed on MacOS ? Have you ever done it on windows 10?

**Comment by valoricDe** [comment]
Yes I transfered a file from phone to dellmac and saw in the window or the activity monitor that it was showing a speed around 400mb/s. I haven't tested on windows. But I only experienced it after using the settings from this repo. So I thought there has to be some setting which influences this.
But if you do not know just close, I can live with it :D

**Comment by intel0753** [comment]
I suggest you should test disk speed with Blackmagic Disk Speed Test, it is available on the Mac App Store for free. Different types of storage device can affect the disk speed result. Besides, I wonder which phone you are using, it can even reach a speed of 400 MB/s?
