### ISSUE TITLE
Sidecar does not work.

### ISSUE THREAD

**Issue by pramjan90** [jardenliu/XPS15-9560-Catalina#110]
Sidecar was working fine until a month back, when I was using it. Then, after not using it for a while, **Sidecar suddenly stopped working** with my iPad, and I have no way of re-enabling it.
A full OS reinstall did not help (with latest updates and Clover). Would be great if this can be re-enabled.
Thanks a ton for sharing this repo!

**Comment by SilentSliver** [comment]
Sidecar is a function depends on what networks card you use now and whether it works normally in macOS (both Bluetooth and Wi-Fi) if you use it under wireless environment.
I use DW1830 and sidecar works normally.

**Comment by pramjan90** [comment]
Hi,
Thanks for the quick response!
I use an external wifi [dongle](https://www.tp-link.com/en/home-networking/adapter/archer-t3u/), which worked fine for me the last few months. Since DW1560/DW1830 are not easily available in my country.
Also, I was using Sidecar with USB cable - but it stopped working right now. Does "Handoff" functionality work for you in the system settings?

**Comment by SilentSliver** [comment]
yes, handoff works perfectly with DW1830.

**Comment by jardenliu** [comment]
@pramjan90, As @SilentSliver said, Built-in network card (DW1830/DW1560/DW1820A) works perfectly for Sidecar. recommend DW1830
