### ISSUE TITLE
Higher Minimum Brightness

### ISSUE THREAD

**Issue by pramjan90** [jardenliu/XPS15-9560-Catalina#111]
Hi,
I have noticed that after the update to _Catalina 10.15.4_ recently, and then updating to the latest release from this repo (commit 78, 25 March 2020), the XPS screen lowest brightness has become much higher.
I also use Windows 10 (via dual boot), which has the correct lowest brightness setting.
Can you help resolve this issue please?

Regards.

**Comment by SilentSliver** [comment]
Maybe some Function has changed in System so that the backlight level has been affected.
[Uploading 0329-JardenLiu-CLOVER-Test-Backlight-Level-Rewrite.zip…](This is a Beta version for test backlight level)
You can try it and reply in this thread if you found some issues.

**Comment by SilentSliver** [comment]
[0329-JardenLiu-CLOVER-Test-Backlight-Level-Rewrite.zip](https://github.com/jardenliu/XPS15-9560-Catalina/files/4398181/0329-JardenLiu-CLOVER-Test-Backlight-Level-Rewrite.zip)
sorry and this is the attachment.
