### ISSUE TITLE
No audio in through headphone jack

### ISSUE THREAD

**Issue by ant-ds** [jardenliu/XPS15-9560-Catalina#113]
Hi,

When I plug in a microphone through the headphone jack, it is not recognized as an audio input in system preferences. I tried to use different devices to be sure: 
- Microphone only device (purple colored jack)
- Windows headset (audio+microphone through the jack)
- iPhone compatible headset (this normally doesn't work on the XPS but I tried just in case)

Would there be an easy fix for this?
The internal microphone is working without issues. Audio out through headphone jack works without issues.

PS: thank you for this amazing repo. It helped me a ton, my XPS seems to work flawlessly!

**Comment by jardenliu** [comment]
After installed system, have you ever tried to install `ALC298PluginFix` ?

**Comment by jardenliu** [comment]
if installation was failed, try to exec `sudo mount -uw /`

**Comment by ant-ds** [comment]
Thank you for the quick response. I installed the ALC298PluginFix by double clicking the `install双击自动安装.command`

I think that went successfully if my Google Translate isn't lying:
`安装ALCPlugFix守护进程完成！
重建缓存中，请稍候……
KernelCache ID: D4832C26337C5D27F22180ACA1377325
安装程序结束，请重启电脑！！！
按任何键退出`

Still no input is recognized through headphone jack (tested again with the 3 devices mentioned above + tested on a Macbook Air to be sure that the devices work).

**Comment by jardenliu** [comment]
I suddenly remembered that device input didn't seem to work all the time.  Recommend you to use the Bluetooth microphone.
