### ISSUE TITLE
Error in config.plist

### ISSUE THREAD

**Issue by riccardomidali** [jardenliu/XPS15-9560-Catalina#116]
Hi,
I'm trying to fix icloud and facetime in clover, but when I open config.plist it shows this error:
<img width="1260" alt="Schermata 2020-04-11 alle 03 36 28" src="https://user-images.githubusercontent.com/63498341/79041762-97f5ec80-7bf2-11ea-85c2-30c85536aa06.png">
<img width="1260" alt="Schermata 2020-04-11 alle 03 36 51" src="https://user-images.githubusercontent.com/63498341/79041764-99bfb000-7bf2-11ea-8474-1804ed1e4361.png">
how can I fix it?

**Comment by SilentSliver** [comment]
Remove Line <key>BootGraphics</key> and Synchronize

**Comment by riccardomidali** [comment]
Thanks, it worked. Now I have another problem: 
the ethernet, which initially worked, now doesn't. It shows this error
<img width="780" alt="Screenshot 2020-04-12 at 08 11 09" src="https://user-images.githubusercontent.com/63498341/79069767-204abf00-7cd1-11ea-9951-a3f80bf6cb8c.png">

This happened after I followed [this guide](https://hackintosher.com/guides/quick-fixes-facetime-icloud-imessage-hackintosh-not-working/) -> https://hackintosher.com/guides/quick-fixes-facetime-icloud-imessage-hackintosh-not-working/

maybe for 
_sudo rm -rf /Library/Preferences/SystemConfiguration/NetworkInterfaces.plist
sudo rm -rf /Library/Preferences/SystemConfiguration/preferences.plist_

how can I fix it?

**Comment by jardenliu** [comment]
USB WiFi adaptor cannot do that

**Comment by riccardomidali** [comment]
I'm not using WIFI adaptor but an ethernet adaptor, and before I did that it worked...

**Comment by jardenliu** [comment]
Just Built-in Ethernet LAN cards can fix `facetime ` `iMessage`

**Comment by SilentSliver** [comment]
Try to readd your connection? I’m not very sure this could be helpful.
