### ISSUE TITLE
No audio and Ethernet

### ISSUE THREAD

**Issue by vinayakUs** [jardenliu/XPS15-9560-Catalina#117]
No audio and Ethernet device showing up
![15866161873365306277530357872221](https://user-images.githubusercontent.com/52126811/79046862-eaee9480-7c30-11ea-8d0e-e2a875d5b87f.jpg)

**Comment by SilentSliver** [comment]
The device only have a fake ethernet, or use a real hub to connect with RJ45 port. But Mac don't have the driver, so it needs a driver (.pkg).
About Audio if you don't change audio part, it won't loss. So please more details
