### ISSUE TITLE
OpenCore branch isn't working? 

### ISSUE THREAD

**Issue by DanielToubul** [jardenliu/XPS15-9560-Catalina#118]
Hello guys, 
While this repo helped me get my XPS 9560 working with clover bootloader (Thanks for that btw!)
I get errors when trying to boot the installer using the files in OpenCore branch.
Can I get an example of how to use it? 
Thanks in advance.
D

**Comment by SilentSliver** [comment]
OC branch needs update. 
To be honest, because it’s  hard to debug some issues in oc and usually I couldn’t boot in macOS with oc. If you need, I can give you a test version configuration to try to boot in system.

**Comment by DanielToubul** [comment]
Yes I would be glad to test it.

**Comment by SilentSliver** [comment]
[0414-SilentSliver-OpenCore-Test.zip](https://github.com/jardenliu/XPS15-9560-Catalina/files/4475149/0414-SilentSliver-OpenCore-Test.zip)
This Config has been tested. Before using it, please READ README first to avoid some issues which could cause boot failure.

**Comment by DanielToubul** [comment]
Thank you for your fast response. 

I have configured it and tried again with the new config and there was a boot error.
**_Now_** after I've changed the config.plist to allow AppleXcpmCfgLock and IgnoreInvalidFlexRatio (cause I couldn't find in the bios the function of disabling CFGlock) I'm after half of the post to the installation, **but it halted in the middle.**
I couldn't find FileValue Encryption option in the bios as well, so it might be it. (maybe there is a workaround in the plist like the other options?) 
Attaching here a screen shot of the log.
Thanks,
D.
![IMG_6616](https://user-images.githubusercontent.com/26459151/79238647-4d85a180-7e78-11ea-872a-65bec7a98c8d.jpg)

**Comment by SilentSliver** [comment]
Yes, because I just think this could be quick for you to use opencore but yes it has some bug 🌚. I have been fix these errors now, but it still has some issues. 
I always test configurations with turning Off FileVault, and if you want to use this function, you need enable some quirks in config.

**Comment by DanielToubul** [comment]
> Yes, because I just think this could be quick for you to use opencore but yes it has some bug 🌚. I have been fix these errors now, but it still has some issues.
> I always test configurations with turning Off FileVault, and if you want to use this function, you need enable some quirks in config.

Where is filevault located in the bios? I have searched for it for 3 times and couldn't find it. maybe it was removed in late bios versions?

**Comment by SilentSliver** [comment]
After you open the FileVault, I think you can only boot you PC with OC or Clover with Some Quirks open in OC\config.plist. (Im not sure because in Clover FileVault has very bad performance, so I always close it). Maybe you need ENABLE ALL OPTIONS BELOW if you want to use fv:
Misc → Security
AuthRestart = YES
UEFI → Input
KeySupport = YES
UEFI → Protocals
FirmwareVolume = YES
AppleSmcIo = YES
ProvideConsoleGOP = YES
RequestBootVarRouting = YES
 HashServices = YES
(If you boot and meet this tip `Still waiting for root device`, you should open this) ExitBootServicesDelay = 5
At last, even if OC we still suggest that DO NOT OPEN FILEVAULT ON HACKINTOSH, it will cause many unexpected bugs.

**Comment by SilentSliver** [comment]
I have been commit latest  version OCConfig which has fixed all boot Error(Except FileVault). You can try it waiting for commit been merged directly update with this attachment below.
[0415-SilentSliver-Opencore.zip](https://github.com/jardenliu/XPS15-9560-Catalina/files/4482838/0415-SilentSliver-Opencore.zip)

**Comment by SilentSliver** [comment]
Sorry and please use this one. 
[0415-SilverSliver-OpenCore-Test.zip](https://github.com/jardenliu/XPS15-9560-Catalina/files/4483519/0415-SilverSliver-OpenCore-Test.zip)

**Comment by DanielToubul** [comment]
Hey there, 
I was quite busy, I tested the new one you have sent and it didn't work well. 
But, I have made a workaround in the first config you have sent and it is working quite well.
The only issues with it right now is: 
1. SMBIOS section in the platform-tools is false as in OC there is a different workaround using Gen-SMBIOS software to create a a working serial, but there is another spoofing method in the config.plist that have to be changed for that to happen.
**So as of now, iServices are not working.** 
2. Trackpad gestures are not working 100%. 
It was working in clover, so probably a problem with some of the ACPI connecting with VOODOOI2c

D.

**Comment by DanielToubul** [comment]
[Opencore Working EFI 15-4-2020.zip](https://github.com/jardenliu/XPS15-9560-Catalina/files/4487793/Opencore.Working.EFI.15-4-2020.zip)

**Comment by doanquanvietnamca** [comment]
just replace EFI folder ?

**Comment by SilentSliver** [comment]
> Hey there,
> I was quite busy, I tested the new one you have sent and it didn't work well.
> But, I have made a workaround in the first config you have sent and it is working quite well.
> The only issues with it right now is:
> 
> 1. SMBIOS section in the platform-tools is false as in OC there is a different workaround using Gen-SMBIOS software to create a a working serial, but there is another spoofing method in the config.plist that have to be changed for that to happen.
>    **So as of now, iServices are not working.**
> 2. Trackpad gestures are not working 100%.
>    It was working in clover, so probably a problem with some of the ACPI connecting with VOODOOI2c
> 
> D.

iService you mean iMessage and FaceTime? To use these services you must edit config and generate a right inform(like serial number, rom, mlb and uuid(from windows).you can try opencore configurator). Or you couldn’t use these services normally. It’s easy.
Trackpad issue has been test. After test I’ll commit the newest patch.

**Comment by DanielToubul** [comment]
> just replace EFI folder ?

As mentioned in my last comment: "I was quite busy, I tested the new one you have sent and it didn't work well."



> > Hey there,
> > I was quite busy, I tested the new one you have sent and it didn't work well.
> > But, I have made a workaround in the first config you have sent and it is working quite well.
> > The only issues with it right now is:
> > 
> > 1. SMBIOS section in the platform-tools is false as in OC there is a different workaround using Gen-SMBIOS software to create a a working serial, but there is another spoofing method in the config.plist that have to be changed for that to happen.
> >    **So as of now, iServices are not working.**
> > 2. Trackpad gestures are not working 100%.
> >    It was working in clover, so probably a problem with some of the ACPI connecting with VOODOOI2c
> > 
> > D.
> 
> iService you mean iMessage and FaceTime? To use these services you must edit config and generate a right inform(like serial number, rom, mlb and uuid(from windows).you can try opencore configurator). Or you couldn’t use these services normally. It’s easy.
> Trackpad issue has been test. After test I’ll commit the newest patch.

OK I'm waiting for the newest commit. 
10X

**Comment by SilentSliver** [comment]
I have committed, you can try the new one after merged when you free. On my laptop trackpad works very well now
😁

**Comment by DanielToubul** [comment]
> I have committed, you can try the new one after merged when you free. On my laptop trackpad works very well now
> 😁

Waiting for it to be online, it looks like it is waiting for the confirmation of jardenliu

**Comment by DanielToubul** [comment]
Hey there! 
An update ->
Everything works perfectly in the lastest EFI folder commit! (even hotswap usb devices!) 
After generating SMBIOS information with opencore configirator even iServices are working well now.
 **I might want to add some tools + information on the readme file if you'd like that.** 
So we can basically close this case.
But a bit unrelated I noticed one bug / issue: When connecting the charger there might be a random power surge that will cause the device to restart.
This has been tested in the bios also, and in the bios environment this behavior could not replicate itself.
Thank you very much for your hard & fast work you are amazing!

**Comment by SilentSliver** [comment]
Yes, the power issue i think it come from clover? I’m not really sure but I know it’s a video port identity issue. You can plugin your earphone and when your earphone works normally, the issue could be avoided. 
I will try to fix this but might will take some time.

**Comment by SilentSliver** [comment]
And welcome for your commit.
