### ISSUE TITLE
Bluetooth

### ISSUE THREAD

**Issue by doanquanvietnamca** [jardenliu/XPS15-9560-Catalina#123]
How can i make bluetooth work ?

**Comment by SilentSliver** [comment]
which Bluetooth card

**Comment by intel0753** [comment]
You need to specify your BT card model and the screenshot including the BT status and your sysinfo.

**Comment by doanquanvietnamca** [comment]
<img width="751" alt="Screenshot 2020-04-19 at 15 46 23" src="https://user-images.githubusercontent.com/47383746/79688156-0a9b4380-8255-11ea-9c01-2422f463cb78.png">
it is info sys

**Comment by SilentSliver** [comment]
Please REMOVE ALL KEXTS and BOOT-ARGS which always contain “bcm” or “brcm” (in boot args also have “bpr”), if you are using intel wireless card.
Then inject intel Bluetooth kext and place them in `CLOVER/Kexts/Other` for Mac. For more details please search the project in Github.

**Comment by doanquanvietnamca** [comment]
> Please REMOVE ALL KEXTS and BOOT-ARGS which always contain “bcm” or “brcm” (in boot args also have “bpr”), if you are using intel wireless card.
> Then inject intel Bluetooth kext and place them in `CLOVER/Kexts/Other` for Mac. For more details please search the project in Github.

thanks you so much for this. It's work. But now i cannot sign in into app store

**Comment by SilentSliver** [comment]
You MUST make you wireless card at en0, or use a fake Ethernet, (As we know intel cards still have some issues, so it’s a bad idea to choose the intel ones.)but I’m not very sure the step details.  
For more detail you can search on Google or bing, might be helpful.

**Comment by doanquanvietnamca** [comment]
i use another card, it is not problem. This is working perfect with new config. just app store not working

**Comment by jardenliu** [comment]
set the ethernet card to `en0 ` for app store verification

**Comment by doanquanvietnamca** [comment]
i change to en0 end it work. thanks you
