### ISSUE TITLE
Fake Builtin Ethernet Works

### ISSUE THREAD

**Issue by keysun11952** [jardenliu/XPS15-9560-Catalina#125]
I managed to get a fake builtin ethernet (en0) working using NullEthernet Kext and SSDT
Could be helpful for those who don't have functioning wifi and still want to use appstore and sidecar
Let me know if you think it is necessary to add that functionality to this project

**Comment by jardenliu** [comment]
Fake build-in ethernet is unnecessary for all users. It is more suitable as an option. 
It is a good way which is put the fake files into `post-install` and make a guide for it.

Welcome to make a new PR.
