### ISSUE TITLE
USB-C Hotplugging

### ISSUE THREAD

**Issue by rhyswilliamsza** [jardenliu/XPS15-9560-Catalina#64]
Hi There!

Thanks for the excellent work. Just a heads up, blazinsmokey on tonymacx86 seems to have got USB-C & TB3 hotplugging working. I've tried to join your repo with some of their changes, however haven't been successful. Just thought I'd bring it to your attention in case it's helpful.

https://www.tonymacx86.com/threads/guide-dell-xps-9560-mojave-virtualsmc-i2c-trackpad-clover-uefi-hotpatch.263567/page-30#post-1947819

--

嗨，您好！

感谢您的出色工作。 只是抬头，tonymacx86上的blazinsmokey似乎已经让USB-C和TB3热插拔工作了。 我试图加入你的回购与他们的一些变化，但是没有成功。 只是觉得如果它有用，我会引起你的注意。

https://www.tonymacx86.com/threads/guide-dell-xps-9560-mojave-virtualsmc-i2c-trackpad-clover-uefi-hotpatch.263567/page-30#post-1947819

**Comment by jardenliu** [comment]
Thanks, I will try it later

**Comment by jimyth01** [comment]
@jardenliu  大哥啥时候更新这个呢，每天刷新这个项目就等你更新了，买了个显卡扩展坞，结果用不了

**Comment by jardenliu** [comment]
@jimyth01 我手头没有雷电3的设备，就没法测试

**Comment by intel0753** [comment]
我手头拥有一个USB-C转换器Dell DA300，是一个标准的USB-C设备，在当前Clover配置下，重建缓存后是可以进行USB-C热插拔的，上面的接口都能正常工作。
在系统报告中，系统没有检测到雷电总线，所以雷电3应该是不能工作的，不知道先将雷电3设备连接至电脑再开机(即冷启动)能否正常工作。
----------------------------
I have a USB-C dongle, Dell DA300, which I think is a proper USB-C device. Using the current Clover folder configuration in this repo, after rebuilding kexts cache it can work properly and hotplugging is always successful.
As for TB3, the system can't detect the Thunderbolt 3 Bus, so it may not work. I wonder if connecting the TB3 devices to XPS15 9560 then press the power button (cold start) will make 
TB3 device work.

**Comment by jardenliu** [comment]
I can't test the driver after I change the config. Because I don't have the Thunderbolt 3 equipment. I'm so sorry about that.

**Comment by yutian12345** [comment]
可以把配置给我试试看，我有TB16
