### ISSUE TITLE
Bluetooth doesn't work anymore :/

### ISSUE THREAD

**Issue by LeLunZ** [jardenliu/XPS15-9560-Catalina#83]
Yeah, again a Bluetooth issue.

On Mac OS it says "Bluetooth: Not Available", even after turning bluetooth off on, from BIOS or other operating system.
It works if I replace USBPorts with the generic USBPower.kext. So it seems like there are some kind of problems...
Already checked the ioreg, Bluetooth is HS04 like you defined in the kext. So there should be nothing wrong... 

Any idea how to fix it?

**Comment by LeLunZ** [comment]
Ah Bluetooth only shows up in ioreg at HS04 with USBPower, not with USBPorts

**Comment by jardenliu** [comment]
The only difference thing between USBPort.kext and USBPower.kext is name. What's your WIFI-Blutooth module? DW1830 ? or ?

**Comment by LeLunZ** [comment]
Yap DW1830. 
Sorry didn’t mean USBpower. It was USBInjectAll.kext.

**Comment by pramjan90** [comment]
Hi, Bluetooth does not work right now, after the latest update to Catalina 10.15.4

**Comment by SilentSliver** [comment]
> Hi, Bluetooth does not work right now, after the latest update to Catalina 10.15.4

Hi! First, forgive me for my poor English. Which Card do you use? DW1830 or DW1560 or Some cards token from MacBook series ?

**Comment by SilentSliver** [comment]
> Yap DW1830.
> Sorry didn’t mean USBpower. It was USBInjectAll.kext.
> 
> I removed com.xxx.Bluetooth.plist. didnt help.
> so I reinstalled the system, because I thought it could be a issue with some kind of program...
> didnt help.

If you have some usb issues with usbport but work normally with usbinjectall, you can re-customizd usbpower.kext or usbport.kext with Hackintool.app
