### ISSUE TITLE
NVME support

### ISSUE THREAD

**Issue by jizongFox** [jardenliu/XPS15-9560-Catalina#89]
Hi, 
Can this repo support Samsung 970 EVO (nvme) ssd disk since you have `东芝 NVMe 512G`.
Thanks!

**Comment by jardenliu** [comment]
This repo always work fine  with Samsung 970 EVO. What‘s problem  with you?

**Comment by jizongFox** [comment]
Based on your comments, I will buy this ssd. Thanks
