### ISSUE TITLE
用这个efi安装了15.1，有几个问题请教一下

### ISSUE THREAD

**Issue by yutian12345** [jardenliu/XPS15-9560-Catalina#90]
1、触控板多点触控不能用，设置触控板为空，需要重建一下缓存，这个已经可用。
2、7700HQ的变频无法使用，用cpu-s测试，只有3.4，3.5，3.6几个睿频频率，没有降频选项，重建缓存后仍然不可用，请问有建议吗？

**Comment by SilentSliver** [comment]
cpu-s的不太准，频率只要能在intel power gadget里最低到0.8就算没问题，触控板我正在试看打kextpatch能不能解决每次升级或安装后重建缓存才能驱动触控板的问题
