### ISSUE TITLE
声卡没有驱动的问题

### ISSUE THREAD

**Issue by demongel** [jardenliu/XPS15-9560-Catalina#93]
版本是1080的，其他差别不大，用外置网卡，没有换dw

替换三码后升级后可以看到白苹果， 但无法启动，将plist中以下
<string>dart=0 darkwake=1 agdpmod=vit9696 brcmfx-country=#a keepsyms=1 -lilubetaall bpr_probedelay=100 bpr_initialdelay=300 bpr_postresetdelay=300</string>
中  -lilubetaall bpr_probedelay=100 bpr_initialdelay=300 bpr_postresetdelay=300
全部去掉就好了，但是声卡没效果。
想问下这一部分启动参数是做什么的， 是否和声卡驱动有关？

**Comment by SilentSliver** [comment]
这部分是蓝牙驱动参数，如果你是外置网卡需要把博通驱动和参数删掉 即带有brcm字样的驱动，和声卡没有关系

**Comment by demongel** [comment]
> 这部分是蓝牙驱动参数，如果你是外置网卡需要把博通驱动和参数删掉 即带有brcm字样的驱动，和声卡没有关系

感谢回复，具体有测试了一下，只有lilubetaall 这一启动项会导致无法启动。 晚上先删了14、15下博通的驱动，plist里不太确定哪些相关，暂时没动，重新跑了下还是没声音，触控板调节音量始终是禁行标志。 尝试换回万能驱动292，注入改为detect，触控板可以调节音量，音乐也可以播放，但是无论调大调小都没有声音。。。。。后面再继续摸索一下。

**Comment by SilentSliver** [comment]
声卡有可能需要重建缓存才可以，先试一下吧，如果还不行有可能需要等到日后换OC彻底解决问题了

**Comment by jardenliu** [comment]
ALCplu装了吗？

**Comment by demongel** [comment]
> ALCplu装了吗？

装了，今天又重装了下，重建缓存。。。突然发现耳机是好的，音量调节也没问题（现在是用万能驱动），就是外放没声音……周末再折腾折腾。
