### ISSUE TITLE
键盘灯大写灯按一下不亮，常按才亮，使用Karabiner-Elements无法警用内置键盘

### ISSUE THREAD

**Issue by sunht6** [jardenliu/XPS15-9560-Catalina#94]
RT键盘是HHBK USB版本 使用Karabiner-Elements的时候勾选
![image](https://user-images.githubusercontent.com/33158976/70960537-48773800-20ba-11ea-97fa-28d5de1b0fe8.png)

无法屏蔽掉这个内置的键盘
还有内置的键盘大写灯按一下不亮，常按才亮，功能是正常的

**Comment by SilentSliver** [comment]
这个问题现在因为不再使用rh而是使用acidanthera的ps2驱动，不清楚解决了没有。
