### ISSUE TITLE
已经升级成功，有几个小问题

### ISSUE THREAD

**Issue by iPermanent** [jardenliu/XPS15-9560-Catalina#96]
1是不管是type c口还是hdmi 只要插或者拔都会引起电脑重启
2是触屏失效了，应该是没有驱动起来
别的暂时没有发现，有一些未知原因引发重启的次数比较多

**Comment by SilentSliver** [comment]
触屏是个例，暂不清楚原因。升级之后是否重建缓存？
重启的话请在弹出的出现问题窗口点击汇报将log贴上，以便定位问题所在

From Silver Sliver
________________________________
发件人: Henry <notifications@github.com>
发送时间: Sunday, December 22, 2019 11:11:46 AM
收件人: jardenliu/XPS15-9560-Catalina <XPS15-9560-Catalina@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [jardenliu/XPS15-9560-Catalina] 已经升级成功，有几个小问题 (#96)


1是不管是type c口还是hdmi 只要插或者拔都会引起电脑重启
2是触屏失效了，应该是没有驱动起来
别的暂时没有发现，有一些未知原因引发重启的次数比较多

―

**Comment by intel0753** [comment]
插拔C口重启算是一个比较常见的问题，解决的方法就是（多次）重建缓存。
我的设备在 Clover 5099 / macOS 10.15.2 的状态下USB-C设备工作正常，可以热插拔。
请检查你的Clover版本，并尝试重建缓存来解决问题。

**Comment by iPermanent** [comment]
触屏问题重建缓存好了，不过type-c和HDMI的问题依旧存在，是否需要更新clover版本

**Comment by SilentSliver** [comment]
可以更新试试，目前已知clover版本会对c口和hdmi有一定影响，但是无法定位具体如何作用

**Comment by iPermanent** [comment]
重新用repo里的文件替换了一下，重建缓存，然后重启 type c口好了，hdmi的就不试了，反正我的显示器是type-c到dp口的，白苹果一直用的c口，嘿嘿。感谢各位
